name: debian-changelog
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'debian/changelog'
      - '.github/**'
defaults:
  run:
    shell: sh
jobs:
  debian-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install --no-install-recommends git-buildpackage
    - uses: actions/checkout@v3

    - name: Get future version
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: none
        WITH_V: false
        DRY_RUN: true
        PRERELEASE_SUFFIX: rc

    - name: Update debian/changelog
      run: |
        export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
        export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
        git config --local user.name "$DEBFULLNAME"
        git config --local user.email "$DEBEMAIL"
        test -s debian/changelog || ( dch --create --package test --newversion ${{ steps.taggerDryRun.outputs.new_tag }} --empty && git add debian/changelog )
        gbp dch --help
        # dch --package test --newversion ${{ steps.taggerDryRun.outputs.new_tag }} --empty && git add debian/changelog 
        gbp dch -c --ignore-branch --new-version ${{ steps.taggerDryRun.outputs.new_tag }} --verbose --debian-tag='%(version)s' --upstream-tag='%(version)s'
        # git push
        # echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      env:
        TZ: UTC0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
