name: debian-changelog
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'debian/changelog'
      - '.github/**'
defaults:
  run:
    shell: sh
jobs:
  debian-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends git-buildpackage
      - uses: actions/checkout@v3

      - name: Tag
        id: taggerDryRun
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "main"
          release_strategy: "none"
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update debian/changelog
      run: |
        export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
        export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
        git config --local user.name "$DEBFULLNAME"
        git config --local user.email "$DEBEMAIL"
        test -s debian/changelog || ( dch --create --package test --newversion ${{ steps.taggerDryRun.outputs.new_tag }} --empty && git add debian/changelog )
        dch --package test --newversion ${{ steps.taggerDryRun.outputs.new_tag }} --empty && git add debian/changelog
        cat debian/changelog 
        # gbp dch --help
        # gbp dch --ignore-branch --new-version ${{ steps.taggerDryRun.outputs.new_tag }} --verbose --debian-tag='%(version)s' --upstream-tag='%(version)s'
        gbp dch --ignore-branch --verbose --debian-tag='%(version)s' --upstream-tag='%(version)s'
        cat debian/changelog 
      env:
        TZ: UTC0

    - name: "Commit all changed files back to the repository"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--signoff'
        push_options: '--force'
