name: Push Create Tag
"on":
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  merge:
    name: Push Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: Update debian/control
        if: ${{ steps.semver.outputs.next != '' }}
        run: |
          VERSION=$(echo ${{ steps.semver.outputs.next }} | sed 's/^v//')
          sed "/^Version:/c\\Version:\ ${VERSION}" -i debian/control

      - name: Update debian/changelog
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.debian.toml
          args: --tag ${{ steps.semver.outputs.next }}
        env:
          OUTPUT: debian/changelog

      - name: Update CHANGELOG.md
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.git.toml
          args: --tag ${{ steps.semver.outputs.next }}
        env:
          OUTPUT: CHANGELOG.md

      # - name: Commit changelogs & version
      #   if: ${{ steps.semver.outputs.next != '' }}
      #   uses: stefanzweifel/git-auto-commit-action@v5.0.1
      #   with:
      #     branch: main
      #     commit_message: 'docs: update changelogs & version for ${{ steps.semver.outputs.nextStrict }}'
      #     file_pattern: CHANGELOG.md debian/changelog debian/control

      # - name: "Create New Tag"
      #   if: ${{ steps.semver.outputs.next != '' }}
      #   uses: mathieudutour/github-tag-action@v6.2
      #   with:
      #     github_token: ${{ secrets.PAT }}
      #     custom_tag: ${{ steps.semver.outputs.next }}
      #     tag_prefix: ""


      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        if: ${{ steps.semver.outputs.next != '' }}
        with:
          # add: 'CHANGELOG.md debian/changelog debian/control'
          commit: --signoff
          default_author: github_actor
          fetch: false
          message: 'docs: update changelogs & version for ${{ steps.semver.outputs.next }} [skip ci]'
          tag: '${{ steps.semver.outputs.next }} --force'
          tag_push: '--force'
