name: Push Rebase - main
"on":
  push:
    branches:
      - main
concurrency:
  group: push-rebase-main
  cancel-in-progress: true
jobs:
  rebase:
    name: Push Rebase - main
    runs-on: ubuntu-latest
    steps:
      - name: Rebase all pull requests on push to the main branch
        if: "${{ startsWith(github.event.head_commit.message, 'docs: update changelogs & version for ') }}"
        uses: peter-evans/rebase@v3.0.0
        with:
          base: main
          exclude-drafts: true
          exclude-labels: |
            no-rebase
            dependencies
