name: Push Create Tag
"on":
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  merge:
    name: Push Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: Update debian/control
        if: ${{ steps.semver.outputs.next != '' }}
        run: |
          VERSION=$(echo ${{ steps.semver.outputs.next }} | sed 's/^v//')
          sed "/^Version:/c\\Version:\ ${VERSION}" -i debian/control

      - name: Update temporary (unreleased) debian/changelog
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.debian.toml
          args: --unreleased --tag ${{ steps.semver.outputs.next }}
        env:
          OUTPUT: .debian-changelog.unreleased

      - name: Update temporary (current) debian/changelog
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.debian.toml
          args: --current
        env:
          OUTPUT: .debian-changelog.current

      - name: Update debian/control
        if: ${{ steps.semver.outputs.next != '' }}
        run: |
          cat .debian-changelog.unreleased > debian/changelog
          cat .debian-changelog.current >> debian/changelog
          rm -rfv .debian-changelog.*

      - name: Update temporary (unreleased) CHANGELOG.md
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.git.toml
          args: --unreleased  --tag ${{ steps.semver.outputs.next }}
        env:
          OUTPUT: .CHANGELOG.md.unreleased

      - name: Update temporary (current) CHANGELOG.md
        if: ${{ steps.semver.outputs.next != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: .cliff.git.toml
          args: --current
        env:
          OUTPUT: .CHANGELOG.md.current

      - name: Update CHANGELOG.md
        if: ${{ steps.semver.outputs.next != '' }}
        run: |
          cat .CHANGELOG.md.unreleased > CHANGELOG.md
          cat .CHANGELOG.md.current >> CHANGELOG.md
          rm -rfv .CHANGELOG.md.*

      - name: Commit changelogs
        if: ${{ steps.semver.outputs.next != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: update changelogs & version for ${{ steps.semver.outputs.nextStrict }}'
          file_pattern: CHANGELOG.md debian/changelog debian/control

      - name: "Create New Tag"
        if: ${{ steps.semver.outputs.next != '' }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""
