name: Auto Tag my Application
on:
  pull_request:
    types:
      - closed
    branches:
      - main
concurrency: production
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Tag
        id: taggerDryRun
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "main"
          release_strategy: "release"
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
