name: Auto Tag my Application
on:
  pull_request:
    types:
      - closed
    branches:
      - main
concurrency: production
jobs:
  Patch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends git-buildpackage
      - uses: actions/checkout@v3

      - name: Check Tag
        id: taggerDryRun
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "main"
          release_strategy: "none"
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update debian/changelog
        run: |
          export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
          export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
          git config --local user.name "$DEBFULLNAME"
          git config --local user.email "$DEBEMAIL"
          test -s debian/changelog || ( dch --create --package test --newversion ${{ steps.taggerDryRun.outputs.tag }} --empty && git add debian/changelog )
          dch --help
          dch -i --ignore-branch --new-version ${{ steps.taggerDryRun.outputs.tag }} 
          # gbp dch --help
          gbp dch --ignore-branch --new-version ${{ steps.taggerDryRun.outputs.tag }} --debian-tag='%(version)s' --upstream-tag='%(version)s'
          cat debian/changelog 
        env:
          TZ: UTC0

      - name: "Commit all changed files back to the repository"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--signoff'
          push_options: '--force'
          branch: "main"

      - name: Apply Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "main"
          release_strategy: "release"
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
