name: Tag Release
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends git-buildpackage

      - name: Update debian/changelog
        run: |
          export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
          export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
          git config --local user.name "$DEBFULLNAME"
          git config --local user.email "$DEBEMAIL"
          #
          # if [ -s debian/changelog ]; then
          #   if [ $(head -n 1 debian/changelog | grep -c 'UNRELEASED;') == 1 ]; then
          #     sed -i 's|UNRELEASED;|unstable;|' debian/changelog;
          #   else
          #     echo "No UNRELEASED version!"
          #     exit 1;
          #   fi
          # else
          #   dch --package test --create --newversion ${{ steps.semver.outputs.nextStrict }} --empty
          # fi
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo ${VERSION}
          gbp dch --ignore-branch --new-version ${VERSION} --debian-tag='v%(version)s' --upstream-tag='v%(version)s' --full
          git add debian/changelog
          cat debian/changelog
        env:
          TZ: UTC0


      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.PAT }}

      - name: Commit changelogs
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: update changelogs for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md debian/changelog
