name: Tag Release
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update debian/changelog
        uses: orhun/git-cliff-action@v3
        id: changelog-debian
        with:
          config: .cliff.debian.toml
        env:
          OUTPUT: debian/changelog

      - name: Update debian/control
        run: |
          VERSION=$(echo ${{ steps.changelog-debian.outputs.version }} | sed 's/^v//')
          sed "/^Version:/c\\Version:\ ${VERSION}" -i debian/control

      # - name: Update release CHANGELOG
      #   id: release-changelog
      #   uses: requarks/changelog-action@v1.10.2
      #   with:
      #     token: ${{ github.token }}
      #     tag: ${{ github.ref_name }}

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     allowUpdates: true
      #     draft: false
      #     makeLatest: false
      #     name: ${{ github.ref_name }}
      #     body: ${{ steps.release-changelog.outputs.changes }}
      #     token: ${{ secrets.PAT }}

      - name: Update CHANGELOG.md
        uses: orhun/git-cliff-action@v3
        id: changelog-git
        with:
          config: cliff.git.toml
        env:
          OUTPUT: CHANGELOG.md

      - name: Update .CHANGELOG.md
        uses: orhun/git-cliff-action@v3
        id: changelog-release
        with:
          config: cliff.release.toml
          args: --current --strip all
        env:
          OUTPUT: .CHANGELOG.md

      - name: Commit changelogs
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: update changelogs & version for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md debian/changelog debian/control .CHANGELOG.md

