name: Tag Release
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update debian/changelog
        uses: orhun/git-cliff-action@v3
        id: debian-changelog
        with:
          config: cliff.toml
        env:
          OUTPUT: debian/changelog

      - name: Update debian/control
        run: |
          # export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
          # export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
          # git config --local user.name "$DEBFULLNAME"
          # git config --local user.email "$DEBEMAIL"
          # #
          # VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          # echo ${VERSION}
          # #
          sed "/^Version:/c\\Version:\ ${{ steps.debian-changelog.outputs.version }}" -i debian/control
        env:
          TZ: UTC0

      - name: Update release CHANGELOG
        id: release-changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: false
          name: ${{ github.ref_name }}
          body: ${{ steps.release-changelog.outputs.changes }}
          token: ${{ secrets.PAT }}

      - name: Commit changelogs
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: update changelogs & versions for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md debian/changelog debian/control
