name: Tag Release
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update release description .CHANGELOG.md
        uses: orhun/git-cliff-action@v3
        id: changelog-release
        with:
          config: .cliff.release.toml
          args: --current --strip all
        env:
          OUTPUT: .CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog-release.outputs.content }}
          token: ${{ secrets.PAT }}

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=source

      - name: list files
        run: |
          ls -la debian/artifacts

      - name: Publish to PPA
        uses: yuezk/publish-ppa-package@dev
        with:
          repository: "zimniy/test"
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          tarball: debian/artifacts/*.tar.*
          debian_dir: debian
          deb_email: "zimniy@cyberbrain.pw"
          deb_fullname: "Dmitriy Safronov"
          series: "mantic"
          extra_series: "jammy noble"
          # revision: ${{ inputs.revision }}
